// apps/react/src/App.tsx
import { Button } from "@poc-mitosis/library-react";
import { MyComponent } from "@poc-stencil/library-react";

function App() {
  return (
    <main>
      <h1>REACT - Components</h1>

      <h2>MitosisJS</h2>
      <Button xClick={() => alert("Hello")}>Button</Button>

      <h2>StencilJS</h2>
      <MyComponent first="John" middle="James" last="Doe" />
    </main>
  );
}

export default App;

// apps/angular/src/app/app.component.ts
import { APP_INITIALIZER, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { Button } from '@poc-mitosis/library-angular/dist';
// import { defineCustomElements } from '@poc-stencil/library/loader';
import { MyComponent } from '@poc-stencil/library-angular/dist';

@Component({
  standalone: true,
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  imports: [RouterOutlet, Button, MyComponent],
})
export class AppComponent {
  title = 'angular';

  public handleClick() {
    alert('Hello');
  }
}

<main>
  <h1>ANGULAR -Components</h1>
  <h2>MitosisJS</h2>
  <x-button (xClick)="handleClick()">Button</x-button>

  <h2>StencilJS</h2>
  <my-component first="John" middle="James" last="Doe"></my-component>
</main>
